apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: whoami03-ingress
  namespace: whoami
spec:
  rules:
  - host: whoami03.test.scaleme.io
    http:
      paths:
      - backend:
          service:
            name: whoami03
            port:
              name: web
        path: /
        pathType: Prefix

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: whoami03
  namespace: whoami
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  selector:
    app: whoami03
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: whoami03
  name: whoami03
  namespace: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami02
  template:
    metadata:
      labels:
        app: whoami02
    spec:
      containers:
      - image: traefik/whoami
        imagePullPolicy: Always
        name: whoami02
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
